apiVersion: v1
kind: Service
metadata:
  name: hazelcast-client-service
spec:
  selector:
    app: hazelcast-client
  ports:
    - protocol: TCP
      port: 8764
      targetPort: 8764
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-client-deployment
  labels:
    app: hazelcast-cluster
spec:
  selector:
    matchLabels:
      app: hazelcast-client
  replicas: 1
  template:
    metadata:
      labels:
        app: hazelcast-client
    spec:
      containers:
        - name: hazelcast-client-1
          image: gcr.io/hazelcast-cluster/hazelcast-client-k8s:latest
          imagePullPolicy: Always
          env:
          - name: EUREKA_URI
            value: http://eureka:admin@eureka-service:8761/eureka
          - name: POD_IP
            valueFrom:
             fieldRef:
              fieldPath: status.podIP
          ports:
          - containerPort: 8764